/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.terasology.gradle.plugin;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;
import java.nio.file.Files;

import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * A simple functional test for the 'org.terasology.gradle.plugin.greeting' plugin.
 */
public class TerasologyPluginFunctionalTest {
    @Test
    public void canRunTask() throws IOException {
        // Setup the test build
        File projectDir = new File("build/functionalTest");
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        writeString(new File(projectDir, "build.gradle"),
                "plugins {" +
                        "  id('java')\n " +
                        "  id('TerasologyPlugin')" +
                        "}");

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("jar");
        runner.withProjectDir(projectDir);
        BuildResult result = runner.build();

        // Verify the result
        result.getTasks().forEach(
                (t) ->System.out.println(t.getOutcome() + ":" + t.getPath())
        );
        //assertTrue(result.getOutput().contains("Hello from plugin 'org.terasology.gradle.plugin.greeting'"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
