/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.terasology.gradle.plugin;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'org.terasology.gradle.plugin.greeting' plugin.
 */
public class TerasologyPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
//        Project project = ProjectBuilder.builder().build();
//        project.getPlugins().apply("org.terasology.gradle.plugin.TerasologyPlugin");
//
//        // Verify the result
//        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
